### PR TITLE
Package Updates

### PR DESCRIPTION
**Pull request by rye**
Here's 6 months of updates… lint and prettier are happy now.

### CODE REVIEW

**Comment by hawkrives** [comment]
Why did we gain a top-level `word-wrap` dependency?

**Comment by rye** [comment]
Because `require('word-wrap')` was failing.

**Comment by rye** [comment]
Auto DevOps is broken on this project so I disabled GitLab CI for this project by deleting the push mirror over on gitlab.com.

We can explore a mixed DevOps approach some other time.

**Comment by hawkrives** [comment]
What is requiring that? My local greps say server/formats/fasta/build and server/formats/genbank-to-fasta, but those should both be covered by the word-wrap dependency inside of server/package.json

**Comment by rye** [comment]
Ah, yes, that was the server tests broken because I didn't `npm i` in server.

**Comment by rye** [comment]
Unsurprisingly, it still works:

image

**Pull request merged**
