### PR TITLE
Save user settings

### PR DESCRIPTION
**Pull request by OmarShehata**
This just adds the dependency `electron-settings` and uses it to load whatever server url you last used.

I did this because as I'm packaging the app for Windows users, I realized a common user error will be to launch and click run right away, but non developers likely won't have a local server running. The best way to handle it for both dev's and non dev's is to simply load whatever you last used, and I imagine we might need to save similar settings for convenience in the future.

### CODE REVIEW

**Comment by hawkrives** [comment]
I would rather just change the default to one of the CS servers than add ~3000 lines of code in the dependencies, TBH.

**Comment by OmarShehata** [comment]
My opinion is being able to save configuration variables is a good thing.

**Comment by hawkrives** [comment]
But we don't have to have any configuration variables.

We only have one, right now, and AFAIK none of our future plans require any additional options in the UI.

**Comment by hawkrives** [comment]
If we add even a second configuration option, we'll use this. (And you'll get to say "I told you so!".)

**Comment by OmarShehata** [comment]
Yeah that's fair. Thanks for the quick review!

**Comment by hawkrives** [comment]
@OmarShehata I've changed my mind on this, but I can't reopen b/c the branch is deleted. Do you mind re-pushing?

**Comment by OmarShehata** [comment]
I don't have it, but feel free to [install it](https://github.com/nathanbuchar/electron-settings).

**Pull request closed without merging**
