### PR TITLE
Add FASTA builder/parser module

### LINKED ISSUE #40: Create functions to parse and generate FASTA files
The GENBANK parser should then output the data in the parsed data format expected by the FASTA generator, so all FASTA parsing and generation is handled by the same code.

### PR DESCRIPTION
**Pull request by hawkrives**
Closes #40 

I also added a new dependency, `expect`, which is really nice for writing tests. I also wrote simple tests for this new module.

Usage:

```js
const {parseFasta} = require('../lib/fasta')

const output = parseFasta(`
> Emydura_subglobosa__KC755190
ggaacaataaattatcacctcaaaagacac

> Emydura_victoriae__KC755189
ggaacaatcaattattaccccacaaagac

> Emydura_victoriae__KC755188
ggaacaatcaattattaccccacaaggaa
`)

output === [
  { species: 'Emydura_subglobosa__KC755190', sequence: 'ggaacaataaattatcacctcaaaagacac' },
  { species: 'Emydura_victoriae__KC755189', sequence: 'ggaacaatcaattattaccccacaaagac' },
  { species: 'Emydura_victoriae__KC755188', sequence: 'ggaacaatcaattattaccccacaaggaa' },
]
```

```js
const {buildFasta} = require('../lib/fasta')

const output = buildFasta([
  { species: 'Emydura_subglobosa__KC755190', sequence: 'ggaacaataaattatcacctcaaaagacac' },
  { species: 'Emydura_victoriae__KC755189', sequence: 'ggaacaatcaattattaccccacaaagac' },
  { species: 'Emydura_victoriae__KC755188', sequence: 'ggaacaatcaattattaccccacaaggaa' },
])

output === `> Emydura_subglobosa__KC755190
ggaacaataaattatcacctcaaaagacac
> Emydura_victoriae__KC755189
ggaacaatcaattattaccccacaaagac
> Emydura_victoriae__KC755188
ggaacaatcaattattaccccacaaggaa`
```

### CODE REVIEW

**Comment by hawkrives** [comment]
@rye I guess it's just inertia. 

Let's approach this from the viewpoint of someone trying to reproduce our results in ten years: will npm still exist? Will docker hub?

If we can reliably build the native modules we depend on (clustal et. all), and we have known locations for those (say, under this org) then someone could build the pipeline and run it manually, even without docker. 

If we don't bundle the node_modules somewhere… where will they come from?

With that said, I think I'd be happy making a distinction between our "production" and "development" dependencies, maybe. It's less of an issue if our test harness is lost than if our core newick parser vanished, say. 

Ramble ramble. Thoughts?

**Comment by rye** [comment]
> Let's approach this from the viewpoint of someone trying to reproduce our results in ten years: will npm still exist? Will docker hub?

Depends on how people take Node in the future, but based on my understanding it feels like the existence of NPM and Docker Hub are safe assumptions to make.

> If we can reliably build the native modules we depend on (clustal et. all), and we have known locations for those (say, under this org) then someone could build the pipeline and run it manually, even without docker.

We do have a place for these particular things, which is (as you say) this GitHub organization.  My thought at this point is that vendored dependencies that we would like to hold onto for a long time should go into this organization.  This way, we control them.  Not only do we control the upgrade process, but we also control the source code—for those which are licensed to allow such behavior, we can just modify the source code and all will be well.

> With that said, I think I'd be happy making a distinction between our "production" and "development" dependencies, maybe. It's less of an issue if our test harness is lost than if our core newick parser vanished, say.

Noting that one will affect us far more than the other, I'd say it's safe to assume that anything in `node_modules` is ignorable.  If we need a dependency to stick around, then we probably would benefit from locking it and controlling versions manually.  Thus, vendoring is more convenient.

> If we don't bundle the node_modules somewhere… where will they come from?

This circles back to your point about the distinction between "development" and "production" dependencies.  I think a test framework, which would live in `node_modules`, could definitely stay in `node_modules`, and we could ignore that entire tree.  Any dependencies (say, a Newick Tree parser) could sit in a vendor folder somewhere and stay idle.

**Comment by rye** [comment]
I should add: it doesn't really affect me one way or the other, but it definitely clogs up the Git history after a while, especially if we're committing changes to these dependencies in with actual work.

**Comment by hawkrives** [comment]
Let's not merge this yet; I'd like to take a stab at separating out runtime from development dependencies tomorrow.

**Comment by hawkrives** [comment]
Or something. I still don't know where Electron fits in with this whole vendoring  thing.

**Comment by hawkrives** [comment]
@rye This is now ready for review

**Pull request merged**
