### PR TITLE
Upgrade pip when building Docker image

### LINKED ISSUE #84: Python wheels fail to build, yet build succeeds?
```
Step 6/9 : RUN pip install -r requirements.txt
 ---> Running in 369cc7c6b7fb
Collecting biopython==1.66 (from -r requirements.txt (line 1))
  Downloading biopython-1.66.tar.gz (13.7MB)
Collecting numpy==1.14.2 (from -r requirements.txt (line 2))
  Downloading numpy-1.14.2-cp27-cp27mu-manylinux1_x86_64.whl (12.1MB)
Collecting seqmagick==0.6.2 (from -r requirements.txt (line 3))
  Downloading seqmagick-0.6.2.tar.gz (40kB)
Building wheels for collected packages: biopython, seqmagick
  Running setup.py bdist_wheel for biopython: started
  Running setup.py bdist_wheel for biopython: finished with status 'error'
  Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-28ZYgs/biopython/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmp_qrRWDpip-wheel- --python-tag cp27:
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help

  error: invalid command 'bdist_wheel'

  ----------------------------------------
  Failed building wheel for biopython
  Running setup.py clean for biopython
  Running setup.py bdist_wheel for seqmagick: started
  Running setup.py bdist_wheel for seqmagick: finished with status 'error'
  Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-28ZYgs/seqmagick/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpHc0LqTpip-wheel- --python-tag cp27:
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help

  error: invalid command 'bdist_wheel'

  ----------------------------------------
  Failed building wheel for seqmagick
  Running setup.py clean for seqmagick
Failed to build biopython seqmagick
Installing collected packages: biopython, numpy, seqmagick
  Running setup.py install for biopython: started
    Running setup.py install for biopython: finished with status 'done'
  Running setup.py install for seqmagick: started
    Running setup.py install for seqmagick: finished with status 'done'
Successfully installed biopython-1.66 numpy-1.14.2 seqmagick-0.6.2
Removing intermediate container 369cc7c6b7fb
 ---> 40b622df2f9f
```

From my reading, it seems like this might be due to a dumbly out-of-date version of `pip` being installed by Debian. (Big surprise.)

### PR DESCRIPTION
**Pull request by rye**
Seems like this solves the problem identified in #84.

Results in a passing build with no error messages locally.

Closes #84.

### CODE REVIEW

**Comment by rye** [comment]
Thought: can we just put `pip` into the `requirements.txt` with a locked version?  Will pip self-upgrade in that way?

**Comment by hawkrives** [comment]
Regarding the thoughts: yes, it would.

**Comment by rye** [comment]
I think that's a better idea, because then we wouldn't trigger a new rebuild every time.

**Comment by rye** [comment]
Here's a pass on this that reverts the changes to the Dockerfile and locks in a version of pip that is recent in `requirements.txt`.

**Comment by rye** [comment]
Actually, that didn't work.  Got the old error messages again.  Reverting.

**Comment by hawkrives** [comment]
Oh right, because we're installing the package with the errors in the same run as pip, we'll still be using the old pip.

**Comment by hawkrives** [comment]
We can also just install `pip install wheel` to install the package that's missing (whose missing presence causes those errors)

**Comment by rye** [comment]
81faf55 fixes the main issue there, but now we get a complaint about `numpy`.
```
Step 6/9 : RUN pip install -r requirements.txt
 ---> Running in acf528f60835
Collecting biopython==1.66 (from -r requirements.txt (line 1))
  Downloading biopython-1.66.tar.gz (13.7MB)
Collecting numpy==1.14.2 (from -r requirements.txt (line 2))
  Downloading numpy-1.14.2-cp27-cp27mu-manylinux1_x86_64.whl (12.1MB)
Collecting seqmagick==0.6.2 (from -r requirements.txt (line 3))
  Downloading seqmagick-0.6.2.tar.gz (40kB)
Building wheels for collected packages: biopython, seqmagick
  Running setup.py bdist_wheel for biopython: started
  Running setup.py bdist_wheel for biopython: finished with status 'error'
  Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-820moU/biopython/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmppN1VHvpip-wheel- --python-tag cp27:
  running bdist_wheel
  running build
  running build_py

  Numerical Python (NumPy) is not installed.

  This package is required for many Biopython features.  Please install
  it before you install Biopython. You can install Biopython anyway, but
  anything dependent on NumPy will not work. If you do this, and later
  install NumPy, you should then re-install Biopython.

  You can find NumPy at http://www.numpy.org


  ----------------------------------------
  Failed building wheel for biopython
  Running setup.py clean for biopython
  Running setup.py bdist_wheel for seqmagick: started
  Running setup.py bdist_wheel for seqmagick: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/b8/e4/74/a67ed376570090e4d2f489cec35f44f712325038ce35e614e7
Successfully built seqmagick
Failed to build biopython
Installing collected packages: biopython, numpy, seqmagick
  Running setup.py install for biopython: started
    Running setup.py install for biopython: finished with status 'done'
Successfully installed biopython-1.66 numpy-1.14.2 seqmagick-0.6.2
Removing intermediate container acf528f60835
 ---> 1fc9c6da6f41
```

**Comment by rye** [comment]
See [this passing build](https://circleci.com/gh/hybsearch/hybsearch/1154).

**Comment by hawkrives** [comment]
Let's go with the other solution, then (upgrading pip), even though I don't know why that fixes everything.

**Pull request merged**
