### PR TITLE
Restructure project (spring cleaning) 🛀

### PR DESCRIPTION
**Pull request by hawkrives**
- Removes `node_modules`
- Removes `vendor/` folder
- Moves all server code into `/server` (worker and websocket server)
- Moves ent and hamdis code to `/server/lib`
- Extracts the CLI wrappers from the program scripts in bin/ – they now live in scripts/
- Migrates ent tests to jest
- Circle: Removes build->ent link – ent doesn't need docker to run, just node
- Adds eslint and prettier to the codebase, and to Circle

I apologize for the size of this PR, but there was a lot of stuff to remove.

If you want to review it, I'd recommend getting this branch and looking at it locally, instead of trying to use the diff view.

### CODE REVIEW

**Comment by rye** [comment]
Please note that this will significantly decrease our ability to run the server locally without Docker, as this PR removes a bunch of our vendored code and dependencies.

The solution to this is just to use Docker for local development, haha.

**Comment by hawkrives** [comment]
Well, all you'll need is `pip install -r requirements.txt && npm install && node server/server.js` if you don't want Docker, but you'll also have to install the various native dependencies too… so, yeah. Use Docker.

**Comment by hawkrives** [comment]
Or Debian.

**Comment by rye** [comment]
(But not necessarily Ubuntu, despite the fact that it'd probably work on Ubuntu)

**Pull request merged**
