### PR TITLE
Exclude completely distinct genes

### PR DESCRIPTION
**Pull request by OmarShehata**
This PR prunes the resulting newick tree and removes genes that are too dissimilar. The new test file `emydura-short-diff.fasta` contains a gene that is from a different species (Emydura_signata__AF113624.1), and so should be excluded from the analysis. 

This also prints out genes that were excluded in case the program is removing too much. Molly, can you review and confirm that this works? 

I just realized that since this pruning happens on the client, the server will perform the ent search on the unpruned tree. Does this lead to issues?

### CODE REVIEW

**Comment by hawkrives** [comment]
I think it would be beneficial to implement this on the server side… yeah?

**Comment by mollysrour** [comment]
@OmarShehata, this works! But would we need to change some things to implement it on the server side?

**Comment by OmarShehata** [comment]
@mollysrour theoretically all we need to do is move the `RemoveNodes` call and the standard deviation checks to the `worker.js`. I remember initially trying that but the Newick tree looked different on the server (which doesn't make sense, so I think I'll just try this again, I might be remembering it wrong).

One tricky thing to be aware of is that it's not entirely clear which functions mutate their arguments and which use them to compute something new (for example that the ent search changes the newick tree it gets). We should either be more strict about sticking to pure functions or enforce a documentation standard that each function should have a block comment about what it takes in and what it spits out, especially if we want this to be maintainable for future generations @hawkrives .

**Comment by mollysrour** [comment]
@OmarShehata I definitely agree about adding comments for each function, that's a really good idea

**Comment by hawkrives** [comment]
Could you please rename your functions to not start with capital letters if they're not constructors or classes, please?

I agree with comments. I would also not be opposed to reworking the function to be pure. If we don't rework it, we should rename it to, like, `searchMutating` or something.

**Comment by OmarShehata** [comment]
> Could you please rename your functions to not start with capital letters if they're not constructors or classes, please?

[I already did](https://github.com/hybsearch/hybsearch/pull/54/commits/e310b1e2cfea611a421804816d6060177c85af86).

**Comment by hawkrives** [comment]
Okay well in my defense "cleaned up code" isn't a terribly descriptive commit message and I had just looked at it before you pushed that :p

**Comment by hawkrives** [comment]
I'll update this on top of master tomorrow morning.

**Comment by OmarShehata** [comment]
@hawkrives I think this should not be merged yet. We need to:

* Move it to the server so that ent searches the pruned tree, not the original tree.
* Apply the new algorithm for removing things that are too different, even if they are close to their own neighbors.

**Comment by hawkrives** [comment]
@omarshehata Okay. Do you want me to rebase it, or do you think you'll want to start from scratch?

**Comment by OmarShehata** [comment]
@hawkrives you can just leave this branch so I can use it as a reference. I'll make a new branch off of master and submit that for PR.

**Comment by hawkrives** [comment]
I'll close this PR but not delete the branch, then.

**Pull request closed without merging**
